import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, ShieldAlert, XCircle } from "lucide-react";
import { toast } from "sonner";
import { Link } from "wouter";

export default function Approvals() {
  const utils = trpc.useUtils();
  const approvals = trpc.factory.approvals.listOpen.useQuery(undefined, { refetchInterval: 5_000 });
  const resolve = trpc.factory.approvals.resolve.useMutation({ onSuccess: () => { toast.success("Approval recorded."); utils.factory.approvals.listOpen.invalidate(); utils.factory.list.invalidate(); }, onError: error => toast.error(error.message) });
  return <div className="mx-auto max-w-5xl space-y-6 pb-10"><div><p className="font-mono text-xs uppercase tracking-[0.2em] text-amber-300">Approval queue</p><h1 className="mt-2 text-3xl font-semibold text-white">Human control points</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-400">High-impact external actions remain paused until you explicitly decide.</p></div><div className="grid gap-4">{approvals.data?.map(approval => <Card key={approval.id} className="border-amber-300/25 bg-amber-300/[0.06]"><CardContent className="flex flex-col gap-4 p-5 md:flex-row md:items-center md:justify-between"><div className="flex gap-4"><div className="h-fit rounded-xl bg-amber-300/15 p-2.5 text-amber-200"><ShieldAlert className="h-5 w-5" /></div><div><div className="flex flex-wrap items-center gap-2"><Badge className="border-amber-300/30 bg-amber-300/10 text-amber-100">{approval.action.replaceAll("_", " ")}</Badge><Link href={`/projects/${approval.projectId}`} className="text-xs text-cyan-200 hover:underline">Project #{approval.projectId}</Link></div><h2 className="mt-2 text-lg font-semibold text-white">{approval.requestedAction}</h2><p className="mt-1 text-sm leading-6 text-slate-400">{approval.rationale}</p></div></div><div className="flex shrink-0 gap-2"><Button variant="outline" className="border-rose-400/30 bg-rose-500/10 text-rose-100 hover:bg-rose-500/20" disabled={resolve.isPending} onClick={() => resolve.mutate({ approvalId: approval.id, approved: false })}><XCircle className="mr-2 h-4 w-4" />Reject</Button><Button className="bg-amber-300 text-slate-950 hover:bg-amber-200" disabled={resolve.isPending} onClick={() => resolve.mutate({ approvalId: approval.id, approved: true })}><CheckCircle2 className="mr-2 h-4 w-4" />Approve</Button></div></CardContent></Card>)}{!approvals.isLoading && approvals.data?.length === 0 && <Card className="border-slate-800 bg-slate-950/60"><CardHeader className="items-center py-16 text-center"><ShieldAlert className="mb-3 h-9 w-9 text-slate-600" /><CardTitle className="text-white">No approval decisions pending</CardTitle><CardDescription className="max-w-sm text-slate-500">The orchestrator will surface this queue whenever a workflow reaches a protected action.</CardDescription></CardHeader></Card>}</div></div>;
}
