import { useAuth } from "@/_core/hooks/useAuth";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";
import { BellRing, Bot, CheckSquare2, Factory, FolderKanban, LogOut, Menu, X } from "lucide-react";
import { useState } from "react";
import { Link, useLocation } from "wouter";

const nav = [
  { href: "/", label: "Projects", icon: FolderKanban },
  { href: "/approvals", label: "Approvals", icon: CheckSquare2 },
  { href: "/notifications", label: "Alerts", icon: BellRing },
];

export default function FactoryLayout({ children }: { children: React.ReactNode }) {
  const { loading, user, logout } = useAuth();
  const workerStatus = trpc.factory.worker.status.useQuery(undefined, { refetchInterval: 15_000, retry: false, enabled: Boolean(user) });
  const unreadNotifications = trpc.factory.notifications.listUnread.useQuery(undefined, { refetchInterval: 5_000, retry: false, enabled: Boolean(user) });
  const [mobileOpen, setMobileOpen] = useState(false);
  const [location] = useLocation();
  if (loading) return <div className="flex min-h-screen items-center justify-center bg-[#07101d]"><Bot className="h-7 w-7 animate-pulse text-cyan-300" /></div>;
  if (!user) return <div className="flex min-h-screen items-center justify-center bg-[#07101d] px-4"><div className="w-full max-w-md rounded-3xl border border-slate-800 bg-slate-950/70 p-8 text-center shadow-2xl shadow-black/30"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-cyan-300/10 text-cyan-200"><Factory className="h-7 w-7" /></div><h1 className="mt-5 text-2xl font-semibold text-white">Enter the software factory</h1><p className="mt-3 text-sm leading-6 text-slate-400">Sign in to submit requirements, review generated plans, and approve controlled actions.</p><Button className="mt-6 w-full bg-cyan-300 text-slate-950 hover:bg-cyan-200" onClick={() => startLogin()}>Sign in to continue</Button></div></div>;
  return <div className="min-h-screen bg-[#07101d] text-slate-100"><aside className="fixed inset-y-0 left-0 z-40 hidden w-64 border-r border-slate-800 bg-[#081321]/95 px-3 py-5 backdrop-blur lg:flex lg:flex-col"><Brand /><nav className="mt-9 space-y-1">{nav.map(item => <NavItem key={item.href} {...item} badge={item.href === "/notifications" ? unreadNotifications.data?.length : undefined} active={location === item.href || (item.href === "/" && location.startsWith("/projects/"))} />)}</nav><div className="mt-auto rounded-2xl border border-slate-800 bg-slate-900/50 p-3"><div className="flex items-center gap-3"><Avatar className="h-8 w-8 border border-slate-700"><AvatarFallback className="bg-cyan-300/10 text-xs text-cyan-200">{user.name?.slice(0, 1).toUpperCase() ?? "U"}</AvatarFallback></Avatar><div className="min-w-0"><p className="truncate text-xs font-medium text-slate-200">{user.name ?? "Workspace user"}</p><p className="truncate text-[11px] text-slate-500">{user.email ?? "Authenticated"}</p></div></div><Button variant="ghost" className="mt-2 h-8 w-full justify-start px-2 text-xs text-slate-500 hover:bg-slate-800 hover:text-slate-200" onClick={logout}><LogOut className="mr-2 h-3.5 w-3.5" />Sign out</Button></div></aside><header className="sticky top-0 z-30 flex h-16 items-center justify-between border-b border-slate-800 bg-[#07101d]/90 px-4 backdrop-blur lg:ml-64 lg:px-8"><div className="flex items-center gap-3 lg:hidden"><Button variant="ghost" size="icon" className="text-slate-300" onClick={() => setMobileOpen(value => !value)}>{mobileOpen ? <X /> : <Menu />}</Button><span className="text-sm font-semibold text-white">Factory</span></div><div className="hidden lg:block"><p className="font-mono text-[10px] uppercase tracking-[0.2em] text-slate-500">Operational dashboard</p></div><div className="flex items-center gap-2"><Link href="/notifications" className="relative rounded-md p-1.5 text-slate-400 transition hover:bg-slate-800 hover:text-rose-100"><BellRing className="h-4 w-4" />{unreadNotifications.data?.length ? <span className="absolute -right-1 -top-1 min-w-4 rounded-full bg-rose-400 px-1 text-center text-[10px] font-bold leading-4 text-slate-950">{unreadNotifications.data.length}</span> : null}</Link><span className="hidden text-xs text-slate-500 sm:block">{workerStatus.data?.enabled ? "Persistent worker online" : "Worker disabled"}</span><span className={`h-2 w-2 rounded-full shadow-[0_0_12px_rgba(74,222,128,0.8)] ${workerStatus.data?.enabled ? "bg-emerald-400" : "bg-slate-600"}`} /></div></header>{mobileOpen && <div className="fixed inset-x-0 top-16 z-20 border-b border-slate-800 bg-[#081321] p-3 lg:hidden">{nav.map(item => <NavItem key={item.href} {...item} badge={item.href === "/notifications" ? unreadNotifications.data?.length : undefined} active={location === item.href} onClick={() => setMobileOpen(false)} />)}</div>}<main className="min-h-[calc(100vh-4rem)] px-4 py-6 lg:ml-64 lg:px-8 lg:py-8">{children}</main></div>;
}

function Brand() { return <Link href="/" className="flex items-center gap-3 px-2"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-gradient-to-br from-cyan-300 to-violet-400 text-slate-950 shadow-lg shadow-cyan-500/15"><Factory className="h-5 w-5" /></span><span><span className="block text-sm font-semibold tracking-tight text-white">Forgeflow</span><span className="block font-mono text-[9px] uppercase tracking-[0.17em] text-cyan-200/70">software factory</span></span></Link>; }
function NavItem({ href, label, icon: Icon, active, badge, onClick }: { href: string; label: string; icon: typeof FolderKanban; active: boolean; badge?: number; onClick?: () => void }) { return <Link href={href} onClick={onClick} className={`flex h-10 items-center gap-3 rounded-xl px-3 text-sm transition ${active ? "bg-cyan-300/10 text-cyan-100" : "text-slate-500 hover:bg-slate-900 hover:text-slate-200"}`}><Icon className="h-4 w-4" /><span>{label}</span>{badge ? <span className="ml-auto rounded-full bg-rose-400 px-1.5 text-[10px] font-bold leading-4 text-slate-950">{badge}</span> : null}</Link>; }
